# Generated by Django 4.2 on 2025-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shifts', '0003_shift_capacity_shiftswaprequest_assignedshift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
